export const studentUsersSeed = [
  {
    studentId: 'CSE-22-001',
    fullName: 'John Student',
    email: 'john.student@campushub.edu',
    department: 'Computer Science and Engineering',
    year: '3rd Year',
    semester: '6th Semester',
    gpa: 3.75,
    dashboardMeta: { noticesUnread: 3, messagesUnread: 2, coursesEnrolled: 6 },
  },
  {
    studentId: 'CSE-22-002',
    fullName: 'Ayesha Rahman',
    email: 'ayesha.rahman@campushub.edu',
    department: 'Computer Science and Engineering',
    year: '3rd Year',
    semester: '6th Semester',
    gpa: 3.89,
    dashboardMeta: { noticesUnread: 2, messagesUnread: 1, coursesEnrolled: 6 },
  },
  {
    studentId: 'EEE-22-015',
    fullName: 'Tanvir Hasan',
    email: 'tanvir.hasan@campushub.edu',
    department: 'Electrical and Electronic Engineering',
    year: '3rd Year',
    semester: '6th Semester',
    gpa: 3.64,
    dashboardMeta: { noticesUnread: 1, messagesUnread: 4, coursesEnrolled: 5 },
  },
  {
    studentId: 'BBA-23-011',
    fullName: 'Nusrat Jahan',
    email: 'nusrat.jahan@campushub.edu',
    department: 'Business Administration',
    year: '2nd Year',
    semester: '4th Semester',
    gpa: 3.72,
    dashboardMeta: { noticesUnread: 4, messagesUnread: 0, coursesEnrolled: 5 },
  },
  {
    studentId: 'CIVIL-21-004',
    fullName: 'Sakib Ahmed',
    email: 'sakib.ahmed@campushub.edu',
    department: 'Civil Engineering',
    year: '4th Year',
    semester: '8th Semester',
    gpa: 3.58,
    dashboardMeta: { noticesUnread: 0, messagesUnread: 1, coursesEnrolled: 4 },
  },
];
